# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('correct_answer_uri', models.CharField(max_length=500)),
                ('wrong_answer_uri', models.CharField(max_length=500)),
                ('correct_answer_explanation', models.CharField(max_length=500)),
                ('wrong_answer_explanation', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Category')),
            ],
        ),
    ]
