# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='correct_answer_source',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='example',
            name='wrong_answer_source',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
